#!/bin/bash

# Include common variables
. "$(dirname ${BASH_SOURCE[0]})/common.bash"

buildkite-header "Building Docker image"
(cd "$ROOT"; buildkite-run make image)

buildkite-header-prompt "Pushing image to Docker registry"
(cd "$ROOT"; buildkite-run make push)
